"""
train_forecast.py — train the logistics-consumption and machine-health models
on the SYNTHETIC datasets and export them as JSON for the browser.

Models
  1. Consumption (fuel L/day, power kWh/day, food kg/day, water L/day):
     gradient-boosted regression trees on weather / crew / activity / season.
     Compared against a seasonal-naive baseline (same day last year) and a
     ridge regression; the best of the three by hold-out MAE is exported (it is
     the GBM, because heating demand saturates and interacts with wind).
  2. Machine health (health points in h = 1..21 days, no maintenance in
     between): one direct multi-horizon GBM on the current health, its 7-day
     slope, vibration, temperature, load, days since maintenance, category and
     the horizon h.

Honesty notes (the UI repeats these)
  * Data is synthetic, generated by generate_dataset.py. Metrics describe how
    well the model recovers a known generating process, not real station
    behaviour.
  * Chronological split: train < 2025-10-02, calibration to 2026-04-02 (used
    ONLY to size the 80 % prediction intervals), test afterwards. Nothing is
    refit on the test window, and interval coverage is reported on test.

Run:  python generate_dataset.py && python train_forecast.py
Writes frontend/public/models/forecast-model.json
"""
from __future__ import annotations

import json
import os

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, r2_score

HERE = os.path.dirname(__file__)
DATA = os.path.join(HERE, "data")
OUT = os.path.join(HERE, "..", "..", "frontend", "public", "models", "forecast-model.json")

TRAIN_END = pd.Timestamp("2025-10-02")
CAL_END = pd.Timestamp("2026-04-02")
STATION_CODE = {"maitri": 0, "bharati": 1}
TARGETS = ["fuel_l", "power_kwh", "food_kg", "water_l"]
FEATURES = ["station", "doy_sin", "doy_cos", "headcount", "temp_c", "wind_kph", "blizzard", "science_activity", "vehicle_hours"]
HEALTH_FEATURES = ["health", "slope7", "vib7", "temp7", "load7", "since", "category", "h"]
HORIZON = 21
N_TREES, LR = 160, 0.07


def r(x, d=4):
    return round(float(x), d)


def export_gbm(model: GradientBoostingRegressor) -> dict:
    trees = []
    for est in model.estimators_[:, 0]:
        t = est.tree_
        trees.append({
            "f": t.feature.tolist(),
            "t": [r(v) for v in t.threshold],
            "l": t.children_left.tolist(),
            "r": t.children_right.tolist(),
            "v": [r(v[0][0], 4) for v in t.value],
        })
    return {"init": r(model.init_.constant_.ravel()[0], 5), "lr": model.learning_rate, "trees": trees}


def predict_json(gbm: dict, x: list[float]) -> float:
    """Reference implementation of the browser evaluator (used for the parity check)."""
    if gbm["type"] == "linear":
        return gbm["intercept"] + sum(c * v for c, v in zip(gbm["coef"], x))
    total = gbm["init"]
    for t in gbm["trees"]:
        i = 0
        while t["f"][i] >= 0:
            i = t["l"][i] if x[t["f"][i]] <= t["t"][i] else t["r"][i]
        total += gbm["lr"] * t["v"][i]
    return total


def season_cols(df: pd.DataFrame) -> pd.DataFrame:
    doy = df["date"].dt.dayofyear
    df["doy_sin"] = np.sin(2 * np.pi * doy / 365.25)
    df["doy_cos"] = np.cos(2 * np.pi * doy / 365.25)
    df["station_code"] = df["station"].map(STATION_CODE)
    return df


def metrics(y, p):
    y, p = np.asarray(y), np.asarray(p)
    return {"mae": r(mean_absolute_error(y, p), 2), "mape_pct": r(np.mean(np.abs(y - p) / y) * 100, 2), "r2": r(r2_score(y, p), 4)}


def train_consumption(df: pd.DataFrame) -> tuple[dict, pd.DataFrame]:
    df = season_cols(df.copy())
    X_cols = ["station_code", "doy_sin", "doy_cos", "headcount", "temp_c", "wind_kph", "blizzard", "science_activity", "vehicle_hours"]
    train = df[df.date <= TRAIN_END]
    cal = df[(df.date > TRAIN_END) & (df.date <= CAL_END)]
    test = df[df.date > CAL_END]
    out = {}
    pred_frame = df[["date", "station"]].copy()
    for tgt in TARGETS:
        gbm = GradientBoostingRegressor(n_estimators=N_TREES, learning_rate=LR, max_depth=3, subsample=0.8, random_state=7)
        gbm.fit(train[X_cols], train[tgt])
        ridge = Ridge(alpha=1.0).fit(train[X_cols], train[tgt])

        # seasonal-naive: the same station on the same calendar day one year earlier
        lookup = df.set_index(["station", "date"])[tgt]
        def naive(frame):
            keys = list(zip(frame["station"], frame["date"] - pd.Timedelta(days=364)))
            return np.array([lookup.get(k, np.nan) for k in keys])
        naive_test = naive(test)
        ok = ~np.isnan(naive_test)

        p_gbm_test = gbm.predict(test[X_cols])
        m = {
            "gbm": metrics(test[tgt], p_gbm_test),
            "ridge": metrics(test[tgt], ridge.predict(test[X_cols])),
            "seasonal_naive": metrics(test[tgt][ok], naive_test[ok]),
        }

        # export whichever of GBM / ridge scored the lower hold-out MAE
        # (the seasonal-naive baseline is a benchmark only, never exported)
        use_ridge = m["ridge"]["mae"] < m["gbm"]["mae"]
        chosen = ridge if use_ridge else gbm
        exported = ({"type": "linear", "intercept": r(ridge.intercept_, 5), "coef": [r(c, 6) for c in ridge.coef_]}
                    if use_ridge else {"type": "gbm", **export_gbm(gbm)})

        # 80 % interval from RELATIVE residuals on the calibration window
        p_cal = chosen.predict(cal[X_cols])
        rel = (cal[tgt].to_numpy() - p_cal) / p_cal
        q10, q90 = np.quantile(rel, [0.10, 0.90])
        p_test = chosen.predict(test[X_cols])
        lo = p_test * (1 + q10)
        hi = p_test * (1 + q90)
        coverage = float(np.mean((test[tgt].to_numpy() >= lo) & (test[tgt].to_numpy() <= hi)))
        imp = chosen.feature_importances_ if not use_ridge else np.abs(ridge.coef_ * train[X_cols].std().to_numpy())
        imp = imp / imp.sum()
        out[tgt] = {
            "model": exported,
            "metrics": m,
            "exported": "ridge" if use_ridge else "gbm",
            "interval": {"q10": r(q10, 4), "q90": r(q90, 4), "nominal": 0.8, "test_coverage": r(coverage, 3)},
            "importance": {f: r(v, 4) for f, v in zip(X_cols, imp)},
        }
        pred_frame[tgt + "_pred"] = chosen.predict(df[X_cols])
        print(f"{tgt:10s} exported={out[tgt]['exported']:5s} gbm MAE={m['gbm']['mae']:8.2f} MAPE={m['gbm']['mape_pct']:.2f}% R2={m['gbm']['r2']:.3f} "
              f"| ridge MAPE={m['ridge']['mape_pct']:.2f}% | naive MAPE={m['seasonal_naive']['mape_pct']:.2f}% | 80% cover={coverage:.2f}")
    return out, pred_frame


def climatology(df: pd.DataFrame) -> dict:
    """Day-of-year means (smoothed with a +-7 day circular window) — the 'expected weather / crew'
    the forecaster feeds the model for future days it cannot observe."""
    clim = {}
    cols = {"temp_c": 1, "wind_kph": 1, "blizzard": 3, "science_activity": 3, "vehicle_hours": 2, "headcount": 1}
    for sid, g in df.groupby("station"):
        g = g.assign(doy=g.date.dt.dayofyear.clip(upper=365))
        by = g.groupby("doy")[list(cols)].mean().reindex(range(1, 366)).interpolate()
        arr = by.to_numpy()
        pad = np.vstack([arr[-7:], arr, arr[:7]])
        sm = np.array([pad[i:i + 15].mean(axis=0) for i in range(365)])
        clim[sid] = {c: [r(v, d) for v in sm[:, j]] for j, (c, d) in enumerate(cols.items())}
    return clim


def build_health_rows(ad: pd.DataFrame) -> pd.DataFrame:
    frames = []
    for mid, g in ad.groupby("machine_id"):
        g = g.sort_values("date").reset_index(drop=True)
        g["slope7"] = (g.health - g.health.shift(7)) / 7
        g["vib7"] = g.vibration_mm_s.rolling(7).mean()
        g["temp7"] = g.temp_c.rolling(7).mean()
        g["load7"] = g.load_pct.rolling(7).mean()
        for h in range(1, HORIZON + 1):
            fut = g.health.shift(-h)
            # keep only windows with no maintenance/fault reset in (t, t+h]
            reset = g.maintenance.rolling(h).sum().shift(-h).fillna(1)
            sub = g.loc[(reset == 0) & fut.notna() & g.slope7.notna(),
                        ["date", "machine_id", "health", "slope7", "vib7", "temp7", "load7", "days_since_maintenance", "category_code"]].copy()
            sub["h"] = h
            sub["target"] = fut[sub.index] - sub.health
            frames.append(sub)
    rows = pd.concat(frames, ignore_index=True)
    return rows.rename(columns={"days_since_maintenance": "since", "category_code": "category"})


def train_health(ad: pd.DataFrame) -> dict:
    rows = build_health_rows(ad)
    train = rows[rows.date <= TRAIN_END]
    cal = rows[(rows.date > TRAIN_END) & (rows.date <= CAL_END)]
    test = rows[rows.date > CAL_END]
    gbm = GradientBoostingRegressor(n_estimators=130, learning_rate=0.09, max_depth=4, subsample=0.6, random_state=11)
    gbm.fit(train[HEALTH_FEATURES], train.target)
    p_cal = gbm.predict(cal[HEALTH_FEATURES])
    p_test = gbm.predict(test[HEALTH_FEATURES])
    # persistence baseline: "health stays where it is"
    base = metrics(test.health + test.target, test.health)
    mdl = metrics(test.health + test.target, test.health + p_test)
    q10s, q90s, cov = [], [], []
    for h in range(1, HORIZON + 1):
        res = (cal.target - p_cal)[cal.h == h]
        q10s.append(r(np.quantile(res, 0.10), 3))
        q90s.append(r(np.quantile(res, 0.90), 3))
        t_res = (test.target - p_test)[test.h == h]
        cov.append(float(np.mean((t_res >= q10s[-1]) & (t_res <= q90s[-1]))))
    print(f"health     GBM MAE={mdl['mae']:.2f} R2={mdl['r2']:.3f} | persistence MAE={base['mae']:.2f} | 80% cover={np.mean(cov):.2f}")
    return {
        "model": {"type": "gbm", **export_gbm(gbm)},
        "metrics": {"gbm": mdl, "persistence": base},
        "interval_by_h": {"q10": q10s, "q90": q90s, "nominal": 0.8, "test_coverage": r(np.mean(cov), 3)},
        "importance": {f: r(v, 4) for f, v in zip(HEALTH_FEATURES, gbm.feature_importances_)},
        "features": HEALTH_FEATURES,
        "horizon": HORIZON,
        "n_train_rows": int(len(train)),
    }


def main():
    log = pd.read_csv(os.path.join(DATA, "synthetic_logistics_daily.csv"), parse_dates=["date"])
    ass = pd.read_csv(os.path.join(DATA, "synthetic_assets_daily.csv"), parse_dates=["date"])

    cons, preds = train_consumption(log)
    health = train_health(ass)

    # ---- chart history the pages plot (last 150 days) ------------------------
    hist = {}
    for sid, g in log.merge(preds, on=["date", "station"]).groupby("station"):
        g = g.tail(150)
        hist[sid] = {
            "dates": [d.strftime("%Y-%m-%d") for d in g.date],
            **{t: [r(v, 1) for v in g[t]] for t in TARGETS},
            **{t + "_pred": [r(v, 1) for v in g[t + "_pred"]] for t in TARGETS},
            "temp_c": [r(v, 1) for v in g.temp_c], "wind_kph": [r(v, 1) for v in g.wind_kph],
            "headcount": [int(v) for v in g.headcount],
            "fuel_stock_l": [int(v) for v in g.fuel_stock_l], "food_stock_kg": [int(v) for v in g.food_stock_kg],
        }
    machines = {}
    for mid, g in ass.groupby("machine_id"):
        g = g.sort_values("date").tail(90)
        machines[mid] = {
            "station": g.station.iloc[0], "category": g.category.iloc[0], "category_code": int(g.category_code.iloc[0]),
            "dates": [d.strftime("%Y-%m-%d") for d in g.date],
            **{c: [r(v, 2) for v in g[c]] for c in ["health", "load_pct", "temp_c", "vibration_mm_s", "fuel_lph"]},
            "since": [int(v) for v in g.days_since_maintenance],
            "maintenance": [int(v) for v in g.maintenance],
        }

    # ---- parity samples so the browser evaluator can be verified -------------
    df = season_cols(log.copy())
    sample = df[df.date > CAL_END].sample(6, random_state=3)
    parity = []
    for _, row in sample.iterrows():
        x = [float(row[c]) for c in ["station_code", "doy_sin", "doy_cos", "headcount", "temp_c", "wind_kph", "blizzard", "science_activity", "vehicle_hours"]]
        parity.append({"x": x, **{t: r(predict_json(cons[t]["model"], x), 3) for t in TARGETS}})

    out = {
        "meta": {
            "synthetic": True,
            "trained_on": "backend/ml/data/synthetic_*.csv (generate_dataset.py, seed 42)",
            "algorithm": f"GradientBoostingRegressor ({N_TREES} trees, depth 3) per consumption target; direct multi-horizon GBM for machine health",
            "data_range": [str(log.date.min().date()), str(log.date.max().date())],
            "train_end": str(TRAIN_END.date()), "calibration_end": str(CAL_END.date()),
            "n_logistics_rows": int(len(log)), "n_asset_rows": int(len(ass)),
            "validated": "hold-out on the final 6 months of SYNTHETIC data only — not validated against real station data",
        },
        "features": ["station", "doy_sin", "doy_cos", "headcount", "temp_c", "wind_kph", "blizzard", "science_activity", "vehicle_hours"],
        "consumption": cons,
        "climatology": climatology(log),
        "health": health,
        "history": hist,
        "machines": machines,
        "parity": parity,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, separators=(",", ":"))
    print("wrote", os.path.normpath(OUT), f"({os.path.getsize(OUT) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
