// src/lib/mockData/mockAlerts.ts
//
// Frontend-only fallback for the dedicated /alerts page, gated by
// NEXT_PUBLIC_USE_MOCK. Matches BackendAlertDetail exactly (see
// lib/backendAdapters.ts) and is loosely consistent with the degraded/
// critical assets already called out in mockGraph.ts (Diesel Generator 2,
// Deep Freezer 2, VSAT Satellite Link, Sewage Treatment Plant on Maitri; AHU
// 1 and GSI Geophysical Instrument on Bharati).
import type { BackendAlertDetail } from '@/lib/backendAdapters'

const hoursAgo = (n: number) => new Date(Date.now() - n * 3600_000).toISOString()

export const mockAlerts: BackendAlertDetail[] = [
  {
    id: 'alert-maitri-001',
    rule_id: null,
    station_id: 'maitri',
    asset_id: 'maitri-deep-freezer-2',
    series_key: 'temp_c',
    severity: 'critical',
    category: 'power',
    message: 'Deep Freezer 2 internal temperature risen to -8°C (setpoint -18°C)',
    value: -8,
    first_seen: hoursAgo(3),
    last_seen: hoursAgo(0.2),
    occurrences: 14,
    state: 'open',
    acked_by: null,
    acked_at: null,
    ack_note: null,
    escalated_at: hoursAgo(1),
  },
  {
    id: 'alert-maitri-002',
    rule_id: null,
    station_id: 'maitri',
    asset_id: 'maitri-genset-2',
    series_key: 'load_factor_pct',
    severity: 'warning',
    category: 'power',
    message: 'Diesel Generator 2 load factor trending above 85% for 3 hours',
    value: 87.4,
    first_seen: hoursAgo(6),
    last_seen: hoursAgo(0.5),
    occurrences: 6,
    state: 'acked',
    acked_by: 'Dev Tester',
    acked_at: hoursAgo(1),
    ack_note: 'Staging Generator 3 as standby',
    escalated_at: null,
  },
  {
    id: 'alert-maitri-003',
    rule_id: null,
    station_id: 'maitri',
    asset_id: 'maitri-comms-vsat',
    series_key: 'link_quality_pct',
    severity: 'warning',
    category: 'security',
    message: 'VSAT link degraded to PNR-isolated during snow squall',
    value: 41,
    first_seen: hoursAgo(30),
    last_seen: hoursAgo(21),
    occurrences: 3,
    state: 'resolved',
    acked_by: 'Dev Tester',
    acked_at: hoursAgo(28),
    ack_note: 'Waiting out the squall',
    escalated_at: null,
  },
  {
    id: 'alert-maitri-004',
    rule_id: null,
    station_id: 'maitri',
    asset_id: 'maitri-stp',
    series_key: 'tank_temp_c',
    severity: 'info',
    category: 'environment',
    message: 'Sewage Treatment Plant bioreactor temperature trending toward lower effective range',
    value: 14.2,
    first_seen: hoursAgo(10),
    last_seen: hoursAgo(1),
    occurrences: 5,
    state: 'open',
    acked_by: null,
    acked_at: null,
    ack_note: null,
    escalated_at: null,
  },
  {
    id: 'alert-bharati-001',
    rule_id: null,
    station_id: 'bharati',
    asset_id: 'bharati-ahu-1',
    series_key: 'filter_dp_pa',
    severity: 'warning',
    category: 'power',
    message: 'AHU 1 filter differential pressure trending above baseline',
    value: 312,
    first_seen: hoursAgo(96),
    last_seen: hoursAgo(2),
    occurrences: 9,
    state: 'open',
    acked_by: null,
    acked_at: null,
    ack_note: null,
    escalated_at: null,
  },
  {
    id: 'alert-bharati-002',
    rule_id: null,
    station_id: 'bharati',
    asset_id: 'bharati-gsi-instrument',
    series_key: 'data_continuity_pct',
    severity: 'warning',
    category: 'science',
    message: 'GSI Geophysical Instrument data continuity dropped below 90% in the last 24h',
    value: 84,
    first_seen: hoursAgo(20),
    last_seen: hoursAgo(3),
    occurrences: 4,
    state: 'open',
    acked_by: null,
    acked_at: null,
    ack_note: null,
    escalated_at: null,
  },
]
